config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :posts do
    collection do
      get 'portfolio'
      get 'myprofile'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
    @post = Post.new
  end

  def portfolio
  end

  def myprofile
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RicoY</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://unpkg.com/sanitize.css"/>     
    <link rel="stylesheet" href="./css/style.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<aside class="profile-card">
  <header>

    <!-- the username -->
    <h1>矢田 理恵子 / Rieko Yata</h1>
    <!-- here’s the avatar -->
    <a target="_blank" href="/">
      <%= image_tag "IMG_5978_Original.jpg", class:"hoverZoomLink" %>
    </a>

  <!-- bit of a bio; who are you? -->
  <ul class="profile-bio">

    <li>＞----<%= link_to 'My Profile', myprofile_posts_path %>----＞</li>
    <li>＞----<%= link_to 'Portfolio', portfolio_posts_path %>----＞</li>
    <li>＞----<a href="https://note.com/ricooooooopin">Output</a>----＞</li>


  </ul>

  <!-- some social links to show off -->
  <ul class="profile-social-links">
    <li>
      <a target="_blank" href="https://twitter.com/Rico26362783">
      <%= image_tag "logo_twitter_bird_icon_143203.png", class:"link-a" %>
      </a>
    </li>
    <li>
      <a target="_blank" href="https://github.com/rieco-y">
      <%= image_tag "logo_github_icon_143196.png", class:"link-a" %>
      </a>
    </li>
  </ul>

  </header>
</aside>

app/views/posts/myprofile.html.erb
<aside class="portfolio-card">

  <main class="main">
    <div class="inner">
    ---------------------------------------
      <h1 class="page-heading">自己紹介</h1>
    ---------------------------------------
    <div class="profiles">
      <div class="face">
          <%= link_to image_tag("IMG_5978_Original.jpg", class:"myface"),"/" %>
      </div>
      <div class="profile">
          <div class="my__body">
            <h2 class="name">矢田理恵子(やたりえこ)</h2>
              <p class="content">・出身地　　：島根県出雲市</p>
              <p class="com">↪︎生粋の出雲人です！</p>
              <p class="content">・年齢　　　：1991年生まれ(30歳)</p>
              <p class="com">↪︎立派な大人になれるよう精進していきます！</p>
              <p class="content">・好きなもの：ドラえもん</p>
              <p class="com">↪︎ドラえもんを開発するのが密かな夢です</p>
              <p class="content">・興味ある事：HTML,CSS,JavaScript</p>
              <p class="com">↪︎クオリティの高いwebページを見ると<br>　webの内容よりもコードが気になります。<br>　HTML,CSSとJavaScriptを自由自在に<br>　使いこなせるようになりたいです！</p>
          </div>
      </div>
    </div>
  </main>


</aside>

app/views/posts/new.html.erb
    <div class="contents row">
    <div class="container">
      <h3>投稿する</h3>
        <%= form_with(model: @post, local: true) do |form| %>
          <%= form.text_field :image, placeholder: "Image Url" %>
          <%= form.text_area :text, placeholder: "text", rows: "10" %>
          <%= form.submit "SEND" %>
        <% end %>
    </div>
  </div>

app/views/posts/portfolio.html.erb
<aside class="portfolio-card">

  <main class="main">
    <div class="inner">
    ---------------------------------------
      <h1 class="page-heading">制作物一覧</h1>
    ---------------------------------------
      <div class="card__wrapper">
        <div class="card">
          <%= link_to image_tag("furima-logo.png", class:"card__img"),"https://furima-36883-new.herokuapp.com/" %>
          <div class="card__body">
            <h2 class="card__title">FURIMA(フリマ)</h2>
            <p class="card__summary">
              ID：doraco 、Pass：1111<br>
              ＜テックキャンプ課題制作＞<br>
              商品の出品・表示・編集・削除・購入<br>
              などを行うフリーマーケットアプリ
            </p>
          </div>
        </div>
        <div class="card">
          <%= link_to image_tag("gjden-logo.png", class:"card__img"),"https://gjden1111.herokuapp.com/" %>
          <div class="card__body">
            <h2 class="card__title">Gjden(ジジデン)</h2>
            <p class="card__summary">
            ID：admin 、PASS：2525<br>
            ＜予約管理アプリ＞<br>
            社内用のお客様情報確認ツール<br>
            MAIL：sasaki@test、PASS：111aaa<br>
            <a href="https://github.com/rieco-y/gjden/blob/master/README.md" class="readme">README</a>
            </p>
          </div>
        </div>
        <div class="card">
          <%= image_tag "image.png", class: "card__img" %>
          <div class="card__body">
            <h2 class="card__title">準備中</h2>
            <p class="card__summary">
              アプリのURL、コンセプト
            </p>
          </div>
        </div>
        <div class="card">
          <%= image_tag "image.png", class: "card__img" %>
          <div class="card__body">
            <h2 class="card__title">準備中</h2>
            <p class="card__summary">
              アプリのURL、コンセプト
            </p>
          </div>
        </div>
        <div class="card">
          <%= image_tag "image.png", class: "card__img" %>
          <div class="card__body">
            <h2 class="card__title">準備中</h2>
            <p class="card__summary">
              アプリのURL、コンセプト
            </p>
          </div>
        </div>
        <div class="card">
          <%= image_tag "image.png", class: "card__img" %>
          <div class="card__body">
            <h2 class="card__title">準備中</h2>
            <p class="card__summary">
              アプリのURL、コンセプト
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>


</aside>